name: dockerComposeTutorialProject
services:
  webappPython:
    build: 
      context: ./pythonApp
      dockerfile: Dockerfile.appPython
    image: webappPython-image
    container_name: webapp-service
    ports:
      - "5000:5000"
  webappNode:
    build: 
      context: ./NodeApp
      dockerfile: Dockerfile.appNode
    image: webappNode-image
    container_name: webappNode-image
    ports:
      - "4000:4000"