events {}

http {
    include mime.types;

    server {
        listen 2026;
        root /usr/share/nginx/html;

        location /date {
        proxy_pass http://backend:3000;
        }
    }
   
}